site_name: "validators"
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://python-validators.github.io/validators/"
repo_url: "https://github.com/python-validators/validators"
edit_uri: "tree/master/docs/"
repo_name: "validators/validators"
site_dir: "site"
watch: [README.md, src/validators/]

nav:
  - Home: index.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
          import:
            - https://docs.python-requests.org/en/master/objects.inv

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/python-validators/validators
