[tool.poetry]
name = "validators"
version = "0.20.0"
description = "Python Data Validation for Humans™"
authors = ["Konsta Vesterinen <konsta@fastmonkeys.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/python-validators/validators"
keywords = ["validation", "validator", "python-validator"]
classifiers = [
    "Development Status :: 4 - Beta",
    'Environment :: Web Environment',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3 :: Only',
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    'Programming Language :: Python :: Implementation :: CPython',
    'Programming Language :: Python :: Implementation :: PyPy',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
    'Topic :: Software Development :: Libraries :: Python Modules',
]

[tool.poetry.dependencies]
python = "^3.9"
decorator = "^5.1.1"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
flake8 = "^6.0.0"
pytest = "^7.2.1"
setuptools = "^67.1.0"
pyright = "^1.1.292"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

################################
# formatters, linters, testers #
################################

[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311']

[tool.tox]
legacy_tox_ini = '''
    [tox]
    requires =
        tox >= 4.0
    env_list = py{39,310,311}
        # format, lint, type,

    [testenv]
    description = run unit tests
    deps = pytest
    commands = pytest

    # [testenv:format]
    # description = run formatter
    # deps = black
    # commands = black

    # [testenv:lint]
    # description = run linters
    # deps = flake8
    # commands = flake8

    # [testenv:type]
    # description = run type checker
    # deps = pyright
    # commands = pyright
'''
