# Documentation
name: docs
on:
  workflow_dispatch:
  push:
    branches: ["master"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
env:
  BUILD_PATH: "."
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # set up specific python version
      - name: Set up Python v3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # building
      - name: Install 'documentation' dependencies
        run: pip install -r python/requirements.mkdocs.txt
      - name: Build documentation
        run: python src/export docs
      # set up Pages
      - name: Set up Pages
        uses: actions/configure-pages@v3
      # upload static page
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.BUILD_PATH }}/site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # deploy documentation
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
