name: PyCodeQualityAnalysis

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  PreflightChecks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # setup specific python version
      - name: Setup Python v${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # install & configure poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      # install dependencies
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --without docs,hooks,sast
      # run preflight checks
      - name: Preflight checks with tox
        run: |
          source .venv/bin/activate
          tox
